import { Restaurant, TableItem, QueueEntry, Reservation, NotificationRecord, StaffMember } from '../types/database';

export const DEFAULT_RESTAURANT: Restaurant = {
  id: 'rest_geetham_001',
  name: 'Geetham Veg Restaurant',
  slug: 'geetham-veg',
  logo_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=120&auto=format&fit=crop&q=80',
  address: '14 Usman Road, T. Nagar, Chennai',
  phone: '+91 44 2815 6789',
  max_party_size: 12,
  created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const INITIAL_TABLES: TableItem[] = [
  // 2-Seaters
  { id: 'tbl_61', restaurant_id: 'rest_geetham_001', table_number: '61', capacity: 2, status: 'AVAILABLE', section: 'Express Diner' },
  { id: 'tbl_62', restaurant_id: 'rest_geetham_001', table_number: '62', capacity: 2, status: 'OCCUPIED', section: 'Express Diner' },
  { id: 'tbl_63', restaurant_id: 'rest_geetham_001', table_number: '63', capacity: 2, status: 'CLEANING', section: 'Express Diner' },
  { id: 'tbl_64', restaurant_id: 'rest_geetham_001', table_number: '64', capacity: 2, status: 'ALLOCATED', section: 'Express Diner' },

  // 4-Seaters
  { id: 'tbl_101', restaurant_id: 'rest_geetham_001', table_number: '101', capacity: 4, status: 'OCCUPIED', section: 'Ground Floor A' },
  { id: 'tbl_102', restaurant_id: 'rest_geetham_001', table_number: '102', capacity: 4, status: 'AVAILABLE', section: 'Ground Floor A' },
  { id: 'tbl_103', restaurant_id: 'rest_geetham_001', table_number: '103', capacity: 4, status: 'OCCUPIED', section: 'Ground Floor A' },
  { id: 'tbl_104', restaurant_id: 'rest_geetham_001', table_number: '104', capacity: 4, status: 'ALLOCATED', section: 'Ground Floor A' },

  // 6-Seaters
  { id: 'tbl_201', restaurant_id: 'rest_geetham_001', table_number: '201', capacity: 6, status: 'OCCUPIED', section: 'Family Hall' },
  { id: 'tbl_202', restaurant_id: 'rest_geetham_001', table_number: '202', capacity: 6, status: 'CLEANING', section: 'Family Hall' },
  { id: 'tbl_203', restaurant_id: 'rest_geetham_001', table_number: '203', capacity: 6, status: 'AVAILABLE', section: 'Family Hall' },
  { id: 'tbl_204', restaurant_id: 'rest_geetham_001', table_number: '204', capacity: 6, status: 'OCCUPIED', section: 'Family Hall' },

  // 8-Seaters
  { id: 'tbl_301', restaurant_id: 'rest_geetham_001', table_number: '301', capacity: 8, status: 'OCCUPIED', section: 'Royal Banquet' },
  { id: 'tbl_302', restaurant_id: 'rest_geetham_001', table_number: '302', capacity: 8, status: 'CLEANING', section: 'Royal Banquet' },
  { id: 'tbl_303', restaurant_id: 'rest_geetham_001', table_number: '303', capacity: 8, status: 'AVAILABLE', section: 'Royal Banquet' },

  // 10-Seaters
  { id: 'tbl_401', restaurant_id: 'rest_geetham_001', table_number: '401', capacity: 10, status: 'OCCUPIED', section: 'Private Dining' },
  { id: 'tbl_402', restaurant_id: 'rest_geetham_001', table_number: '402', capacity: 10, status: 'AVAILABLE', section: 'Private Dining' },

  // 12-Seaters
  { id: 'tbl_501', restaurant_id: 'rest_geetham_001', table_number: '501', capacity: 12, status: 'OCCUPIED', section: 'Grand Pavilion' },
  { id: 'tbl_502', restaurant_id: 'rest_geetham_001', table_number: '502', capacity: 12, status: 'AVAILABLE', section: 'Grand Pavilion' },

  // Extra 4-Seater
  { id: 'tbl_105', restaurant_id: 'rest_geetham_001', table_number: '105', capacity: 4, status: 'CLEANING', section: 'Ground Floor B' },
];

const now = Date.now();
const minAgo = (m: number) => new Date(now - m * 60000).toISOString();
const todayStr = new Date().toISOString().split('T')[0];

export const INITIAL_QUEUE: QueueEntry[] = [
  // ALLOCATED customers
  {
    id: 'queue_517',
    restaurant_id: 'rest_geetham_001',
    token_number: '517',
    queue_date: todayStr,
    customer_name: 'Rahul Sharma',
    phone: '+91 98401 23456',
    email: 'rahul.s@example.com',
    party_size: 2,
    status: 'ALLOCATED',
    position: 0,
    assigned_table_id: 'tbl_64',
    joined_at: minAgo(22),
    allocated_at: minAgo(3),
    notes: 'Requested quiet corner table',
  },
  {
    id: 'queue_518',
    restaurant_id: 'rest_geetham_001',
    token_number: '518',
    queue_date: todayStr,
    customer_name: 'Priya Krishnan',
    phone: '+91 98402 34567',
    email: 'priya.k@example.com',
    party_size: 4,
    status: 'ALLOCATED',
    position: 0,
    assigned_table_id: 'tbl_104',
    joined_at: minAgo(20),
    allocated_at: minAgo(2),
    notes: 'High chair needed for toddler',
  },

  // WAITING customers
  {
    id: 'queue_519',
    restaurant_id: 'rest_geetham_001',
    token_number: '519',
    queue_date: todayStr,
    customer_name: 'Jason Miller',
    phone: '+91 98403 45678',
    email: 'jason.m@example.com',
    party_size: 2,
    status: 'WAITING',
    position: 1,
    joined_at: minAgo(16),
  },
  {
    id: 'queue_520',
    restaurant_id: 'rest_geetham_001',
    token_number: '520',
    queue_date: todayStr,
    customer_name: 'Venkatesh Iyer',
    phone: '+91 98404 56789',
    email: 'venkat.iyer@example.com',
    party_size: 4,
    status: 'WAITING',
    position: 2,
    joined_at: minAgo(14),
  },
  {
    id: 'queue_521',
    restaurant_id: 'rest_geetham_001',
    token_number: '521',
    queue_date: todayStr,
    customer_name: 'Ananya Sen',
    phone: '+91 98405 67890',
    email: 'ananya.sen@example.com',
    party_size: 6,
    status: 'WAITING',
    position: 3,
    joined_at: minAgo(12),
  },
  {
    id: 'queue_522',
    restaurant_id: 'rest_geetham_001',
    token_number: '522',
    queue_date: todayStr,
    customer_name: 'Karthik & Family',
    phone: '+91 98406 78901',
    email: 'karthik.fam@example.com',
    party_size: 8,
    status: 'WAITING',
    position: 4,
    joined_at: minAgo(10),
  },
  {
    id: 'queue_523',
    restaurant_id: 'rest_geetham_001',
    token_number: '523',
    queue_date: todayStr,
    customer_name: 'David Wilson',
    phone: '+91 98407 89012',
    email: 'david.w@example.com',
    party_size: 2,
    status: 'WAITING',
    position: 5,
    joined_at: minAgo(8),
  },
  {
    id: 'queue_524',
    restaurant_id: 'rest_geetham_001',
    token_number: '524',
    queue_date: todayStr,
    customer_name: 'Meenakshi Sundaram',
    phone: '+91 98408 90123',
    email: 'meenakshi@example.com',
    party_size: 5,
    status: 'WAITING',
    position: 6,
    joined_at: minAgo(6),
  },
  {
    id: 'queue_525',
    restaurant_id: 'rest_geetham_001',
    token_number: '525',
    queue_date: todayStr,
    customer_name: 'Sangeetha Patel',
    phone: '+91 98409 01234',
    email: 'sangeetha.p@example.com',
    party_size: 3,
    status: 'WAITING',
    position: 7,
    joined_at: minAgo(5),
  },
  {
    id: 'queue_526',
    restaurant_id: 'rest_geetham_001',
    token_number: '526',
    queue_date: todayStr,
    customer_name: 'Arjun Raman & Team',
    phone: '+91 98410 12345',
    email: 'arjun.r@example.com',
    party_size: 10,
    status: 'WAITING',
    position: 8,
    joined_at: minAgo(4),
  },
  {
    id: 'queue_527',
    restaurant_id: 'rest_geetham_001',
    token_number: '527',
    queue_date: todayStr,
    customer_name: 'Christopher Nolan',
    phone: '+91 98411 23456',
    email: 'c.nolan@example.com',
    party_size: 4,
    status: 'WAITING',
    position: 9,
    joined_at: minAgo(3),
  },
  {
    id: 'queue_528',
    restaurant_id: 'rest_geetham_001',
    token_number: '528',
    queue_date: todayStr,
    customer_name: 'Deepa Balaji',
    phone: '+91 98412 34567',
    email: 'deepa.b@example.com',
    party_size: 2,
    status: 'WAITING',
    position: 10,
    joined_at: minAgo(1),
  },

  // Completed / Seated samples for realistic metrics
  {
    id: 'queue_515',
    restaurant_id: 'rest_geetham_001',
    token_number: '515',
    queue_date: todayStr,
    customer_name: 'Suresh Menon',
    phone: '+91 98413 45678',
    party_size: 4,
    status: 'OCCUPIED',
    assigned_table_id: 'tbl_101',
    joined_at: minAgo(45),
    allocated_at: minAgo(30),
    seated_at: minAgo(28),
  },
  {
    id: 'queue_516',
    restaurant_id: 'rest_geetham_001',
    token_number: '516',
    queue_date: todayStr,
    customer_name: 'Radhika Swaminathan',
    phone: '+91 98414 56789',
    party_size: 2,
    status: 'OCCUPIED',
    assigned_table_id: 'tbl_62',
    joined_at: minAgo(40),
    allocated_at: minAgo(25),
    seated_at: minAgo(22),
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res_001',
    restaurant_id: 'rest_geetham_001',
    customer_name: 'Dr. Subramanian',
    phone: '+91 98415 67890',
    email: 'subramanian@clinic.org',
    party_size: 6,
    reservation_date: todayStr,
    reservation_time: '19:30',
    assigned_table_id: 'tbl_204',
    status: 'CONFIRMED',
    special_requests: 'Anniversary celebration, window table preferred',
    created_at: minAgo(120),
  },
  {
    id: 'res_002',
    restaurant_id: 'rest_geetham_001',
    customer_name: 'Vijay Chandrasekhar',
    phone: '+91 98416 78901',
    email: 'vijay.c@example.com',
    party_size: 8,
    reservation_date: todayStr,
    reservation_time: '20:15',
    assigned_table_id: null,
    status: 'CONFIRMED',
    special_requests: 'Corporate dinner delegation',
    created_at: minAgo(90),
  },
];

export const INITIAL_NOTIFICATIONS: NotificationRecord[] = [
  {
    id: 'wa_init_517',
    restaurant_id: 'rest_geetham_001',
    queue_entry_id: 'queue_517',
    channel: 'WHATSAPP',
    recipient: '+91 98401 23456',
    message: `🎉 Great news!\n\nHello Rahul Sharma! Your table is ready.\nPlease make your way to the host stand.\n\nTable: 64\n\nWe look forward to serving you at Geetham Veg Restaurant!`,
    status: 'SENT',
    created_at: minAgo(3),
  },
  {
    id: 'wa_init_518',
    restaurant_id: 'rest_geetham_001',
    queue_entry_id: 'queue_518',
    channel: 'WHATSAPP',
    recipient: '+91 98402 34567',
    message: `🎉 Great news!\n\nHello Priya Krishnan! Your table is ready.\nPlease make your way to the host stand.\n\nTable: 104\n\nWe look forward to serving you at Geetham Veg Restaurant!`,
    status: 'SENT',
    created_at: minAgo(2),
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  { id: 'stf_01', restaurant_id: 'rest_geetham_001', name: 'Manish Kumar', email: 'manish@geetham.com', role: 'HEAD_HOST', created_at: minAgo(500) },
  { id: 'stf_02', restaurant_id: 'rest_geetham_001', name: 'Kavitha Devi', email: 'kavitha@geetham.com', role: 'WAITER', created_at: minAgo(500) },
  { id: 'stf_03', restaurant_id: 'rest_geetham_001', name: 'Govind Raj', email: 'govind@geetham.com', role: 'WAITER', created_at: minAgo(500) },
];
